name: Build Docker Image

on:
  pull_request:
    branches:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init env
      run: |
        echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
        echo "COMMIT_HASH=${GITHUB_SHA::8}" >> $GITHUB_ENV
        echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

    - name: Render DockerFile template
      run: |
        sh ./render.sh
      env:
        COMMIT_HASH: ${COMMIT_HASH}
        BRANCH: ${BRANCH}
        REPOSITORY_NAME: ${REPOSITORY_NAME}

    - name: Build the Docker image
      run: docker build .

