name: Build And Deploy Docker Image

on:
  push:
    branches:
      - 'master'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init env
      run: |
        echo "REPOSITORY_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
        echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
        echo "DOCKERHUB_IMAGE_NAME=${GITHUB_REPOSITORY_OWNER,,}/${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
        echo "COMMIT_HASH=${GITHUB_SHA::8}" >> $GITHUB_ENV
        echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

    - name: Render DockerFile template
      run: |
        sh ./render.sh
      env:
        COMMIT_HASH: ${COMMIT_HASH}
        BRANCH: ${BRANCH}
        REPOSITORY_NAME: ${REPOSITORY_NAME}

    - name: Build the Docker image
      run: docker build -t "${DOCKERHUB_IMAGE_NAME}:latest" -t "${DOCKERHUB_IMAGE_NAME}:${GITHUB_SHA::8}" .

    - name: Docker login
      run: docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

    - name: Publish image
      run: docker push --all-tags "${GITHUB_REPOSITORY_OWNER,,}/${REPOSITORY_NAME}"

